CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL,
    address VARCHAR(255), phone VARCHAR(30), status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, name VARCHAR(100) NOT NULL,
    nickname VARCHAR(100), phone VARCHAR(30) NOT NULL, gender VARCHAR(20) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'USER', institution_id BIGINT REFERENCES institutions(id),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TIMESTAMP
);

CREATE TABLE care_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institutions(id), name VARCHAR(100) NOT NULL, gender VARCHAR(20) NOT NULL,
    birth_year INTEGER, phone VARCHAR(30), address VARCHAR(255) NOT NULL, detail_address VARCHAR(255),
    latitude NUMERIC(10,7), longitude NUMERIC(10,7), status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    consent_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', consent_at TIMESTAMP, consent_withdrawn_at TIMESTAMP,
    last_checked_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TIMESTAMP
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT REFERENCES users(id), care_recipient_id BIGINT REFERENCES care_recipients(id),
    institution_id BIGINT REFERENCES institutions(id), guest_phone VARCHAR(30), content TEXT NOT NULL,
    address VARCHAR(255), latitude NUMERIC(10,7), longitude NUMERIC(10,7),
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED', embedding VECTOR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE report_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL REFERENCES reports(id),
    s3_key VARCHAR(500) NOT NULL UNIQUE, original_filename VARCHAR(255), content_type VARCHAR(100),
    file_size BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE care_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES care_recipients(id), institution_id BIGINT NOT NULL REFERENCES institutions(id),
    created_by BIGINT NOT NULL REFERENCES users(id), scheduled_at TIMESTAMP NOT NULL,
    required_people INTEGER NOT NULL DEFAULT 2, gender_condition VARCHAR(30) NOT NULL DEFAULT 'NONE',
    status VARCHAR(30) NOT NULL DEFAULT 'RECRUITING', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_care_activities_required_people CHECK (required_people > 0)
);

CREATE TABLE activity_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES care_activities(id), user_id BIGINT NOT NULL REFERENCES users(id),
    application_type VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT REFERENCES users(id), approved_at TIMESTAMP, rejected_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_activity_applications_activity_user UNIQUE (activity_id, user_id)
);

CREATE TABLE activity_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id BIGINT NOT NULL UNIQUE REFERENCES care_activities(id), submitted_by BIGINT REFERENCES users(id),
    checklist_version INTEGER NOT NULL, visit_result VARCHAR(30), started_at TIMESTAMP, completed_at TIMESTAMP,
    special_note TEXT, signature_s3_key VARCHAR(500), signed_at TIMESTAMP,
    review_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', reviewed_by BIGINT REFERENCES users(id),
    reviewed_at TIMESTAMP, review_note TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version INTEGER NOT NULL, code VARCHAR(50) NOT NULL,
    question VARCHAR(500) NOT NULL, item_type VARCHAR(30) NOT NULL, options_json JSONB,
    required BOOLEAN NOT NULL DEFAULT FALSE, sort_order INTEGER NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_checklist_items_version_code UNIQUE (version, code)
);

CREATE TABLE checklist_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_record_id BIGINT NOT NULL REFERENCES activity_records(id), checklist_item_id BIGINT NOT NULL REFERENCES checklist_items(id),
    selected_value VARCHAR(500), text_value TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_checklist_responses_record_item UNIQUE (activity_record_id, checklist_item_id)
);

CREATE TABLE follow_up_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES care_recipients(id), activity_record_id BIGINT REFERENCES activity_records(id),
    institution_id BIGINT NOT NULL REFERENCES institutions(id), created_by BIGINT NOT NULL REFERENCES users(id),
    action_type VARCHAR(50) NOT NULL, content TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mileage_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id),
    activity_record_id BIGINT REFERENCES activity_records(id), type VARCHAR(30) NOT NULL, amount INTEGER NOT NULL,
    reason VARCHAR(255), created_by BIGINT REFERENCES users(id), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_mileage_transactions_amount_nonzero CHECK (amount <> 0)
);

CREATE UNIQUE INDEX uq_mileage_transactions_earn_record_user
    ON mileage_transactions (activity_record_id, user_id) WHERE type = 'EARN';

CREATE TABLE ai_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, analysis_type VARCHAR(50) NOT NULL,
    target_type VARCHAR(30) NOT NULL, target_id BIGINT NOT NULL, result_json JSONB NOT NULL,
    model_name VARCHAR(100), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(255) NOT NULL, content TEXT NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users(id), status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TIMESTAMP
);
